name: Feature Request
description: Request a new feature
title: "Feature: <title>"
labels: ["needs/triage"]
type: Feature

body:
  - type: markdown
    attributes:
      value: |
        ## Requesting a feature
        Thank you for submitting your idea as a feature request! Please make sure to read the [Code of Conduct](https://github.com/The-Mister-X-Project/.github/blob/main/CODE_OF_CONDUCT.md) first.
        Here's a few guidelines to get you started:
          - Pick a descriptive title. This massively increases the chance of the issue being worked on.
          - Fill in all required details as precisely as possible.
          - Don't be frustrated, if we decide not to add your feature request. There might be problems along the way, and after all, everything provided here is free and without warranty.

        ## Request
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: |
        I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Additional Information"
  - type: textarea
    id: additional_context
    attributes:
      label: Screenshots and additional context
      description: Add any other context or screenshots about the feature request here.
